SET TARGET_NAME=Rorohiko Script Runner
SET DESPACED_TARGET_NAME=RorohikoScriptRunner
SET TARGET_DIRNAME=RorohikoScriptRunner
SET TARGET_APP_SELECTED=Any
SET TARGET_APP=Any
SET TARGET_FILENAME_EXTENSION=jsx
SET TARGET_APP_CODE=IDSN
SET TARGET_APP_CPU_WORDSIZE=64
SET TARGET_APP_SCRIPT_DIR=%APPDATA%\Adobe\Any\Version 15.0\en_US\Scripts\Scripts Panel\
SET TARGET_CC_VERSION_SELECTED=Any
SET TARGET_CC_VERSION=2020
SET TARGET_CC_LANGUAGE_CODE=en_US
SET SHORTCODE=RoRu
SET PANELWIDTH=570
SET PANELHEIGHT=200
SET STARTERCODE=ScriptRunner
SET ENABLE_LOG_ENTRY_EXIT=OFF
SET CEPVERSION=6.1
SET APP_MAPPER_SCRIPT=function mapAppId(appId) {var retVal;switch (appId) {case "KBRG":retVal = "Bridge";break;case "DRWV":retVal = "Dreamweaver";break;case "AICY":retVal = "InCopy";break;case "IDSN":retVal = "InDesign";break;case "ILST":retVal = "Illustrator";break;case "PHSH":retVal = "Photoshop";break;case "PPRO":retVal = "Premiere Pro";break;}return retVal;}
SET IMAGEBROWSER_PORT=8000
SET EXTENSION_BUNDLEID=com.rorohiko.sparker
SET EXTENSION_BUNDLENAME=Rorohiko Script Runner
SET EXTENSION_ID=com.rorohiko.sparker.scriptrunner
SET UI_TYPE=Panel
SET EXTENSION_MENUNAME=Rorohiko Script Runner
SET PREFS_FILENAME=RorohikoScriptRunnerPreferences.json
SET DEBUGPORT=8889
SET TARGET_APP_CPU_WORD_SIZE=64
SET TARGET_INDESIGN_VERSION=15.0
SET TARGET_APP_SPECIFIER=indesign-15.064
